package nhom1.ultility;

public interface BookingQuery {
	public static final String INSERT_BOOKING ="INSERT INTO capstone2.bookings(bookings.userId,bookings.servicePackageId,\r\n"
			+ "bookings.price,bookings.deposit,bookings.description,bookings.shootingLocationId,bookings.categoryId,bookings.phoneUser,bookings.note,bookings.takeDate)\r\n"
			+ " VALUES (?,?,?,?,?,?,?,?,?,?)";
		public static final String GET_BOOKING_BY_USER="SELECT * FROM ((( ( (capstone2.bookings inner join servicepackages on bookings.servicePackageId= servicePackages.id ) inner join status_booking on statusBookingId=status_booking.id) inner join photographers on servicePackages.photographerId=photographers.id)inner join provinces on photographers.provinceId=provinces.id) inner join images on servicepackages.id=images.servicePackageId and coverImage=1) where userId=? ORDER BY bookings.createdDate desc LIMIT ?,5";
		public static final String GET_SIZE_BOOKING ="SELECT COUNT(*) FROM  capstone2.bookings  where userId=?";
		public static final String GET_SIZE_BOOKING_BY_STATUSID ="SELECT COUNT(*) FROM  capstone2.bookings  where userId=? AND statusBookingId=?";
		public static final String GET_BOOKING_BY_STATUS="SELECT * FROM ((( ( (capstone2.bookings inner join servicepackages on bookings.servicePackageId= servicePackages.id ) inner join status_booking on statusBookingId=status_booking.id) inner join photographers on servicePackages.photographerId=photographers.id)inner join provinces on photographers.provinceId=provinces.id) inner join images on servicepackages.id=images.servicePackageId and coverImage=1) where userId=? and statusBookingId =? ORDER BY bookings.createdDate desc LIMIT ?,5";
		public static final String GET_BOOKING_BY_USER_SORT_TAKEDATE = "SELECT * FROM ((( ( (capstone2.bookings inner join servicepackages on bookings.servicePackageId= servicePackages.id ) inner join status_booking on statusBookingId=status_booking.id) inner join photographers on servicePackages.photographerId=photographers.id)inner join provinces on photographers.provinceId=provinces.id) inner join images on servicepackages.id=images.servicePackageId and coverImage=1) where userId=? ORDER BY bookings.TAKEDATE desc LIMIT ?,5";
		public static final String GET_BOOKING_BY_STATUS_SORT_TAKEDATE="SELECT * FROM ((( ( (capstone2.bookings inner join servicepackages on bookings.servicePackageId= servicePackages.id ) inner join status_booking on statusBookingId=status_booking.id) inner join photographers on servicePackages.photographerId=photographers.id)inner join provinces on photographers.provinceId=provinces.id) inner join images on servicepackages.id=images.servicePackageId and coverImage=1) where userId=? and statusBookingId =? ORDER BY bookings.TAKEDATE desc LIMIT ?,5";
		public static final String UPDATE_BOOKING="update bookings set bookings.statusBookingId=6,bookings.modifiedDate=now(),statusBeforeCancel=? ,bookings.modifiedBy=? where id=?;";
		public static final String GET_ID_BOOKING ="select  id from bookings where userId=? and servicePackageId=? ORDER BY id DESC LIMIT 1;";
		public static final String GET_STATUS_BOOKING= "select  statusBookingId from bookings where userId=? and servicePackageId=? ORDER BY id DESC LIMIT 1;";
		public static final String GET_BOOKING_BY_PHOTOGRAPHER= "SELECT * FROM ((( ( (capstone2.bookings inner join servicepackages on bookings.servicePackageId= servicePackages.id ) inner join status_booking on statusBookingId=status_booking.id) inner join users on bookings.userId=users.id) inner join provinces on bookings.shootingLocationId=provinces.id) inner join images on servicepackages.id=images.servicePackageId and coverImage=1) where photographerId=? and statusBookingId !=6 ORDER BY bookings.createdDate desc LIMIT ?,5";
		public static final String GET_SIZE_BOOKING_PHOTOGRAPHER ="SELECT COUNT(*) FROM  capstone2.bookings join servicepackages on servicepackages.id=bookings.servicePackageId where photographerId=? and statusBookingId !=6";
		public static final String GET_BOOKING__PHOTOGRAPHER_TAKEDATE ="SELECT * FROM ((( ( (capstone2.bookings inner join servicepackages on bookings.servicePackageId= servicePackages.id ) inner join status_booking on statusBookingId=status_booking.id) inner join users on bookings.userId=users.id) inner join provinces on bookings.shootingLocationId=provinces.id) inner join images on servicepackages.id=images.servicePackageId and coverImage=1) where photographerId=? and statusBookingId !=6 ORDER BY bookings.TAKEDATE desc LIMIT ?,5";
		public static final String GET_SIZE_BOOKING_BY_STATUSID_PHOTOGRAPHER ="SELECT COUNT(*) FROM  capstone2.bookings Inner JOIN servicepackages on bookings.servicePackageId= servicePackages.id  where photographerId=? AND statusBookingId=?";
		public static final String GET_BOOKING_BY_STATUS_FROM_PHOTOGRAPHER="SELECT * FROM ((( ( (capstone2.bookings inner join servicepackages on bookings.servicePackageId= servicePackages.id ) inner join status_booking on statusBookingId=status_booking.id) inner join users on bookings.userId=users.id) inner join provinces on bookings.shootingLocationId=provinces.id) inner join images on servicepackages.id=images.servicePackageId and coverImage=1) where photographerId=? and statusBookingId=? ORDER BY bookings.createdDate desc LIMIT ?,5";
		public static final String GET_BOOKING_BY_STATUS_FROM_PHOTOGRAPHER_SORT_TAKEDATE="SELECT * FROM ((( ( (capstone2.bookings inner join servicepackages on bookings.servicePackageId= servicePackages.id ) inner join status_booking on statusBookingId=status_booking.id) inner join users on bookings.userId=users.id) inner join provinces on bookings.shootingLocationId=provinces.id) inner join images on servicepackages.id=images.servicePackageId and coverImage=1) where photographerId=? and statusBookingId=? ORDER BY bookings.TAKEDATE desc LIMIT ?,5";
		public static final String UPDATE_BOOKING_PHOTOGRAPHER="update bookings set bookings.statusBookingId=?,bookings.modifiedDate=now(),bookings.modifiedBy=? where id=?;";
		public static final String GET_STATUS_BOOKING_BY_ID= "select  statusBookingId from bookings where Id=?";
		public static final String GET_COUNT_BOOKING_NOW="SELECT count(*) FROM capstone2.bookings where userId=? and servicePackageId=? and statusBookingId=?";
		public static final String UPDATE_BOOKING_BY_PRODUCTLINK="update bookings set bookings.statusBookingId=5,bookings.modifiedDate=now(),bookings.productLink=?,bookings.modifiedBy=? where id=?;";
		
}
