package nhom1.ultility;

public interface PhotoOrModelQuery {
	public static final String INSERTPHOTHOGRAPHER = "INSERT INTO capstone2.photographers(photographers.email,photographers.fullName,photographers.nickName, photographers.password,photographers.phone, photographers.roleId,photographers.tokenEmail,photographers.statusAccountId) VALUES (?,?,?,?,?,?,?,2)";
	public static final String ADDIDENTITYPHOTOGRAPHERS = "INSERT INTO identity_photographers(identity_photographers.id,identity_photographers.identityCardNumber,identity_photographers.addressOfId) VALUES (?,?,?)";
	public static final String GETEMAIL = "SELECT * FROM photographers WHERE photographers.email=?";
	public static final String UPDATE_ACTIVEMAIL = "UPDATE photographers SET photographers.statusAccountId=? WHERE photographers.id=?";
	public static final String QUEN_PASSWORD = "UPDATE photographers SET photographers.password =? WHERE photographers.email=?";
	public static final String GET_ALLINFOPHOTO="SELECT * FROM photographers INNER JOIN identity_photographers ON photographers.id= identity_photographers.id WHERE photographers.id=?";
	public static final String UPDATE_PHOTO1 = "UPDATE photographers SET photographers.fullName=?, photographers.phone=?  WHERE photographers.id=?";
	public static final String UPDATE_PHOTO2 = "UPDATE identity_photographers SET identity_photographers.addressOfId=?, identity_photographers.dateOfBirth=?, identity_photographers.gender=?, identity_photographers.identityCardNumber=?  WHERE identity_photographers.id=?";
	public static final String UPDATE_PASSWORD = "UPDATE photographers SET photographers.password =? WHERE photographers.id=?";
	public static final String UPDATE_VIEW = "UPDATE photographers SET photographers.nickName =?,photographers.organize =?,photographers.provinceId =?,photographers.avatar =?,photographers.workPlace =? WHERE photographers.id=?";
	public static final String UPDATE_XM = "UPDATE identity_photographers SET identity_photographers.frontPhoto =?,identity_photographers.backPhoto =?,identity_photographers.fullPhoto =?,identity_photographers.identityVerifyId=2 WHERE identity_photographers.id=?";
	public static final String UPDATEMAPLOCATION= "UPDATE capstone2.location_photographer SET location_photographer.locationx =?,location_photographer.locationy =? WHERE location_photographer.photographerId =?";
	public static final String ADDMAPLOCATION= "INSERT INTO location_photographer (location_photographer.photographerId) VALUES (?)";
	public static final String GETPHOTO ="SELECT * FROM photographers INNER JOIN status_account ON photographers.statusAccountId = status_account.id  ORDER BY photographers.id asc LIMIT ?,10";
	public static final String GETDESCRIBEPHOTOGRAPHER="SELECT * FROM describe_photographer where photographerId=?";
	public static final String GETPHOTOGRAPHERIDENTITY ="SELECT distinct* FROM ((photographers INNER JOIN identity_photographers ON photographers.id = identity_photographers.id) INNER JOIN status_identityverify ON identity_photographers.identityVerifyId=status_identityverify.id) INNER JOIN identity_operaadmin ON identity_operaadmin.photographerId= identity_photographers.id where (identity_photographers.identityVerifyId=2 or identity_photographers.identityVerifyId=3)  ORDER BY photographers.id desc LIMIT ?,10";
	//
	public static final String GETPHOTOGRAPHERIDENTITYBYID ="SELECT distinct * ((photographers INNER JOIN identity_photographers ON photographers.id = identity_photographers.id) INNER JOIN status_identityverify ON identity_photographers.identityVerifyId=status_identityverify.id) INNER JOIN identity_operaadmin ON identity_operaadmin.photographerId= identity_photographers.id where (identity_photographers.identityVerifyId=2 or identity_photographers.identityVerifyId=3) and photographers.id=? ORDER BY photographers.id desc  LIMIT ?,10";

	public static final String GETPHOTOGRAPHERIDENTITYBYSTATUS ="SELECT distinct * FROM ((photographers INNER JOIN identity_photographers ON photographers.id = identity_photographers.id) INNER JOIN status_identityverify ON identity_photographers.identityVerifyId=status_identityverify.id) INNER JOIN identity_operaadmin ON identity_operaadmin.photographerId= identity_photographers.id  where identity_photographers.identityVerifyId=? LIMIT ?,10";
	public static final String COUNTPHOTOIDENTITY="SELECT COUNT(*) FROM photographers INNER JOIN identity_photographers ON photographers.id= identity_photographers.id WHERE identity_photographers.identityVerifyId=2 or identity_photographers.identityVerifyId=3";
	public static final String COUNTPHOTOIDENTITYBYSTATUS="SELECT COUNT(*) FROM photographers INNER JOIN identity_photographers ON photographers.id= identity_photographers.id WHERE identity_photographers.identityVerifyId=?";

	public static final String UPDATE_PASSWORDBYEMAIL = "UPDATE photographers SET photographers.password =? WHERE photographers.email=?";

	public static final String UPDATESTATUS = "UPDATE photographers SET photographers.statusAccountId =? WHERE photographers.id=?";
	//
	public static final String COUNTPHOTO="SELECT COUNT(distinct photographerId) FROM ((photographers INNER JOIN identity_photographers ON photographers.id= identity_photographers.id) INNER JOIN capstone2.servicepackages ON photographers.id = servicepackages.photographerId) INNER JOIN capstone2.provinces ON provinces.id= photographers.provinceId where identity_photographers.identityVerifyId=3 ";
	public static final String COUNTPHOTO1="SELECT COUNT(*) FROM ((photographers INNER JOIN identity_photographers ON photographers.id= identity_photographers.id) INNER JOIN capstone2.servicepackages ON photographers.id = servicepackages.photographerId) INNER JOIN capstone2.provinces ON provinces.id= photographers.provinceId where identity_photographers.identityVerifyId=3 ";
	public static final String COUNTPHOTO2="SELECT COUNT(*) FROM photographers ";
	public static final String SEARCHALLINFOPHOTO="SELECT photographers.id,photographers.fullName,photographers.avatar,photographers.nickName,photographers.provinceId,photographers.workPlace,photographers.organize,identity_photographers.identityVerifyId,photographers.statusAccountId,photographers.countFollower,provinces.provinceName FROM ((photographers INNER JOIN identity_photographers ON photographers.id= identity_photographers.id) INNER JOIN capstone2.servicepackages ON photographers.id = servicepackages.photographerId) INNER JOIN capstone2.provinces ON provinces.id= photographers.provinceId where identity_photographers.identityVerifyId=3 group by photographers.id ORDER BY photographers.id asc LIMIT ?,6 ";
	// search photo
	public static final String SEARCHALLINFOPHOTO1="SELECT photographers.id,photographers.fullName,photographers.avatar,photographers.nickName,photographers.provinceId,photographers.workPlace,photographers.organize,identity_photographers.identityVerifyId,photographers.statusAccountId,photographers.countFollower,provinces.provinceName FROM ((photographers INNER JOIN identity_photographers ON photographers.id= identity_photographers.id) INNER JOIN capstone2.servicepackages ON photographers.id = servicepackages.photographerId) INNER JOIN capstone2.provinces ON provinces.id= photographers.provinceId WHERE photographers.provinceId=? and identity_photographers.identityVerifyId=3 group by photographers.id ORDER BY photographers.id asc LIMIT ?,6 ";
	public static final String SEARCHALLINFOPHOTO2="SELECT photographers.id,photographers.fullName,photographers.avatar,photographers.nickName,photographers.provinceId,photographers.workPlace,photographers.organize,identity_photographers.identityVerifyId,photographers.statusAccountId,photographers.countFollower,provinces.provinceName FROM ((photographers INNER JOIN identity_photographers ON photographers.id= identity_photographers.id) INNER JOIN capstone2.servicepackages ON photographers.id = servicepackages.photographerId) INNER JOIN capstone2.provinces ON provinces.id= photographers.provinceId WHERE servicepackages.categoryId=? and identity_photographers.identityVerifyId=3 group by photographers.id ORDER BY photographers.id asc LIMIT ?,6 ";
	public static final String SEARCHALLINFOPHOTO123="SELECT photographers.id,photographers.fullName,photographers.avatar,photographers.nickName,photographers.provinceId,photographers.workPlace,photographers.organize,identity_photographers.identityVerifyId,photographers.statusAccountId,photographers.countFollower,provinces.provinceName FROM ((photographers INNER JOIN identity_photographers ON photographers.id= identity_photographers.id) INNER JOIN capstone2.servicepackages ON photographers.id = servicepackages.photographerId) INNER JOIN capstone2.provinces ON provinces.id= photographers.provinceId WHERE servicepackages.categoryId=? and identity_photographers.identityVerifyId=3 and photographers.provinceId=? and MATCH(nickName) AGAINST(?) group by photographers.id ORDER BY photographers.id asc LIMIT ?,6 ";
	public static final String SEARCHALLINFOPHOTO12 = "SELECT photographers.id,photographers.fullName,photographers.avatar,photographers.nickName,photographers.provinceId,photographers.workPlace,photographers.organize,identity_photographers.identityVerifyId,photographers.statusAccountId,photographers.countFollower,provinces.provinceName FROM ((photographers INNER JOIN identity_photographers ON photographers.id= identity_photographers.id) INNER JOIN capstone2.servicepackages ON photographers.id = servicepackages.photographerId) INNER JOIN capstone2.provinces ON provinces.id= photographers.provinceId WHERE servicepackages.categoryId=? and identity_photographers.identityVerifyId=3 and photographers.provinceId=? group by photographers.id ORDER BY photographers.id asc LIMIT ?,6";
	public static final String SEARCHALLINFOPHOTO3 = "SELECT photographers.id,photographers.fullName,photographers.avatar,photographers.nickName,photographers.provinceId,photographers.workPlace,photographers.organize,identity_photographers.identityVerifyId,photographers.statusAccountId,photographers.countFollower,provinces.provinceName FROM ((photographers INNER JOIN identity_photographers ON photographers.id= identity_photographers.id) INNER JOIN capstone2.servicepackages ON photographers.id = servicepackages.photographerId) INNER JOIN capstone2.provinces ON provinces.id= photographers.provinceId WHERE identity_photographers.identityVerifyId=3 and MATCH(nickName) AGAINST(?) group by photographers.id ORDER BY photographers.id asc LIMIT ?,6 ";
	public static final String SEARCHALLINFOPHOTO23 = "SELECT photographers.id,photographers.fullName,photographers.avatar,photographers.nickName,photographers.provinceId,photographers.workPlace,photographers.organize,identity_photographers.identityVerifyId,photographers.statusAccountId,photographers.countFollower,provinces.provinceName FROM ((photographers INNER JOIN identity_photographers ON photographers.id= identity_photographers.id) INNER JOIN capstone2.servicepackages ON photographers.id = servicepackages.photographerId) INNER JOIN capstone2.provinces ON provinces.id= photographers.provinceId WHERE servicepackages.categoryId=? and identity_photographers.identityVerifyId=3 and MATCH(nickName) AGAINST(?) group by photographers.id ORDER BY photographers.id asc LIMIT ?,6 ";
	public static final String SEARCHALLINFOPHOTO13 = "SELECT photographers.id,photographers.fullName,photographers.avatar,photographers.nickName,photographers.provinceId,photographers.workPlace,photographers.organize,identity_photographers.identityVerifyId,photographers.statusAccountId,photographers.countFollower,provinces.provinceName FROM ((photographers INNER JOIN identity_photographers ON photographers.id= identity_photographers.id) INNER JOIN capstone2.servicepackages ON photographers.id = servicepackages.photographerId) INNER JOIN capstone2.provinces ON provinces.id= photographers.provinceId WHERE  identity_photographers.identityVerifyId=3 and photographers.provinceId=? and MATCH(nickName) AGAINST(?) group by photographers.id ORDER BY photographers.id asc LIMIT ?,6 ";
	public static final String SEARCHALLINFOPHOTOCARE = "SELECT photographers.id,photographers.fullName,photographers.avatar,photographers.nickName,photographers.provinceId,photographers.workPlace,photographers.organize,identity_photographers.identityVerifyId,photographers.statusAccountId,photographers.countFollower,provinces.provinceName FROM ((photographers INNER JOIN identity_photographers ON photographers.id= identity_photographers.id) INNER JOIN capstone2.servicepackages ON photographers.id = servicepackages.photographerId) INNER JOIN capstone2.provinces ON provinces.id= photographers.provinceId WHERE  identity_photographers.identityVerifyId=3 group by photographers.id  ORDER BY photographers.countFollower desc LIMIT ?,6 ";
	public static final String SEARCHALLINFOPHOTO2CARE = "SELECT photographers.id,photographers.fullName,photographers.avatar,photographers.nickName,photographers.provinceId,photographers.workPlace,photographers.organize,identity_photographers.identityVerifyId,photographers.statusAccountId,photographers.countFollower,provinces.provinceName FROM ((photographers INNER JOIN identity_photographers ON photographers.id= identity_photographers.id) INNER JOIN capstone2.servicepackages ON photographers.id = servicepackages.photographerId) INNER JOIN capstone2.provinces ON provinces.id= photographers.provinceId WHERE servicepackages.categoryId=? and identity_photographers.identityVerifyId=3 group by photographers.id ORDER BY photographers.countFollower desc LIMIT ?,6 ";
	public static final String SEARCHALLINFOPHOTO1CARE = "SELECT photographers.id,photographers.fullName,photographers.avatar,photographers.nickName,photographers.provinceId,photographers.workPlace,photographers.organize,identity_photographers.identityVerifyId,photographers.statusAccountId,photographers.countFollower,provinces.provinceName FROM ((photographers INNER JOIN identity_photographers ON photographers.id= identity_photographers.id) INNER JOIN capstone2.servicepackages ON photographers.id = servicepackages.photographerId) INNER JOIN capstone2.provinces ON provinces.id= photographers.provinceId WHERE photographers.provinceId=? and identity_photographers.identityVerifyId=3 group by photographers.id ORDER BY photographers.countFollower desc LIMIT ?,6 ";
	public static final String SEARCHALLINFOPHOTO12CARE ="SELECT photographers.id,photographers.fullName,photographers.avatar,photographers.nickName,photographers.provinceId,photographers.workPlace,photographers.organize,identity_photographers.identityVerifyId,photographers.statusAccountId,photographers.countFollower,provinces.provinceName FROM ((photographers INNER JOIN identity_photographers ON photographers.id= identity_photographers.id) INNER JOIN capstone2.servicepackages ON photographers.id = servicepackages.photographerId) INNER JOIN capstone2.provinces ON provinces.id= photographers.provinceId WHERE servicepackages.categoryId=? and identity_photographers.identityVerifyId=3 and photographers.provinceId=? group by photographers.id ORDER BY photographers.countFollower desc LIMIT ?,6";
	public static final String SEARCHALLINFOPHOTO3CARE = "SELECT photographers.id,photographers.fullName,photographers.avatar,photographers.nickName,photographers.provinceId,photographers.workPlace,photographers.organize,identity_photographers.identityVerifyId,photographers.statusAccountId,photographers.countFollower,provinces.provinceName FROM ((photographers INNER JOIN identity_photographers ON photographers.id= identity_photographers.id) INNER JOIN capstone2.servicepackages ON photographers.id = servicepackages.photographerId) INNER JOIN capstone2.provinces ON provinces.id= photographers.provinceId WHERE identity_photographers.identityVerifyId=3 and MATCH(nickName) AGAINST(?) group by photographers.id ORDER BY photographers.countFollower desc LIMIT ?,6 ";
	public static final String SEARCHALLINFOPHOTO23CARE = "SELECT photographers.id,photographers.fullName,photographers.avatar,photographers.nickName,photographers.provinceId,photographers.workPlace,photographers.organize,identity_photographers.identityVerifyId,photographers.statusAccountId,photographers.countFollower,provinces.provinceName FROM ((photographers INNER JOIN identity_photographers ON photographers.id= identity_photographers.id) INNER JOIN capstone2.servicepackages ON photographers.id = servicepackages.photographerId) INNER JOIN capstone2.provinces ON provinces.id= photographers.provinceId WHERE servicepackages.categoryId=? and identity_photographers.identityVerifyId=3 and MATCH(nickName) AGAINST(?) group by photographers.id ORDER BY photographers.countFollower desc LIMIT ?,6 ";
	public static final String SEARCHALLINFOPHOTO13CARE = "SELECT photographers.id,photographers.fullName,photographers.avatar,photographers.nickName,photographers.provinceId,photographers.workPlace,photographers.organize,identity_photographers.identityVerifyId,photographers.statusAccountId,photographers.countFollower,provinces.provinceName FROM ((photographers INNER JOIN identity_photographers ON photographers.id= identity_photographers.id) INNER JOIN capstone2.servicepackages ON photographers.id = servicepackages.photographerId) INNER JOIN capstone2.provinces ON provinces.id= photographers.provinceId WHERE  identity_photographers.identityVerifyId=3 and photographers.provinceId=? and MATCH(nickName) AGAINST(?) group by photographers.id ORDER BY photographers.countFollower desc LIMIT ?,6 ";
	public static final String SEARCHALLINFOPHOTO123CARE = "SELECT photographers.id,photographers.fullName,photographers.avatar,photographers.nickName,photographers.provinceId,photographers.workPlace,photographers.organize,identity_photographers.identityVerifyId,photographers.statusAccountId,photographers.countFollower,provinces.provinceName FROM ((photographers INNER JOIN identity_photographers ON photographers.id= identity_photographers.id) INNER JOIN capstone2.servicepackages ON photographers.id = servicepackages.photographerId) INNER JOIN capstone2.provinces ON provinces.id= photographers.provinceId WHERE servicepackages.categoryId=? and identity_photographers.identityVerifyId=3 and photographers.provinceId=? and MATCH(nickName) AGAINST(?) group by photographers.id ORDER BY photographers.countFollower desc LIMIT ?,6 ";
	//count photo
	public static final String COUNTALLINFOPHOTO1="SELECT COUNT(distinct photographerId) FROM ((photographers INNER JOIN identity_photographers ON photographers.id= identity_photographers.id) INNER JOIN capstone2.servicepackages ON photographers.id = servicepackages.photographerId) INNER JOIN capstone2.provinces ON provinces.id= photographers.provinceId WHERE photographers.provinceId=? and identity_photographers.identityVerifyId=3 ";
	public static final String COUNTALLINFOPHOTO2="SELECT COUNT(distinct photographerId) FROM ((photographers INNER JOIN identity_photographers ON photographers.id= identity_photographers.id) INNER JOIN capstone2.servicepackages ON photographers.id = servicepackages.photographerId) INNER JOIN capstone2.provinces ON provinces.id= photographers.provinceId WHERE servicepackages.categoryId=? and identity_photographers.identityVerifyId=3  ";
	public static final String COUNTALLINFOPHOTO123="SELECT COUNT(distinct photographerId) FROM ((photographers INNER JOIN identity_photographers ON photographers.id= identity_photographers.id) INNER JOIN capstone2.servicepackages ON photographers.id = servicepackages.photographerId) INNER JOIN capstone2.provinces ON provinces.id= photographers.provinceId WHERE servicepackages.categoryId=? and identity_photographers.identityVerifyId=3 and photographers.provinceId=? and MATCH(nickName) AGAINST(?)";
	public static final String COUNTALLINFOPHOTO12 = "SELECT COUNT(distinct photographerId) FROM ((photographers INNER JOIN identity_photographers ON photographers.id= identity_photographers.id) INNER JOIN capstone2.servicepackages ON photographers.id = servicepackages.photographerId) INNER JOIN capstone2.provinces ON provinces.id= photographers.provinceId WHERE servicepackages.categoryId=? and identity_photographers.identityVerifyId=3 and photographers.provinceId=? ";
	public static final String COUNTALLINFOPHOTO3 = "SELECT COUNT(distinct photographerId) FROM ((photographers INNER JOIN identity_photographers ON photographers.id= identity_photographers.id) INNER JOIN capstone2.servicepackages ON photographers.id = servicepackages.photographerId) INNER JOIN capstone2.provinces ON provinces.id= photographers.provinceId WHERE identity_photographers.identityVerifyId=3 and MATCH(nickName) AGAINST(?)";
	public static final String COUNTALLINFOPHOTO23 = "SELECT COUNT(distinct photographerId) FROM ((photographers INNER JOIN identity_photographers ON photographers.id= identity_photographers.id) INNER JOIN capstone2.servicepackages ON photographers.id = servicepackages.photographerId) INNER JOIN capstone2.provinces ON provinces.id= photographers.provinceId WHERE servicepackages.categoryId=? and identity_photographers.identityVerifyId=3 and MATCH(nickName) AGAINST(?) ";
	public static final String COUNTALLINFOPHOTO13 = "SELECT COUNT(distinct photographerId) FROM ((photographers INNER JOIN identity_photographers ON photographers.id= identity_photographers.id) INNER JOIN capstone2.servicepackages ON photographers.id = servicepackages.photographerId) INNER JOIN capstone2.provinces ON provinces.id= photographers.provinceId WHERE  identity_photographers.identityVerifyId=3 and photographers.provinceId=? and MATCH(nickName) AGAINST(?) ";

	//search by location
	public static final String SEARCHALLINFOPHOTOBYLOCATION="SELECT photographers.id,photographers.fullName,photographers.avatar,photographers.nickName,photographers.provinceId,photographers.workPlace,photographers.organize,identity_photographers.identityVerifyId,photographers.statusAccountId,photographers.countFollower,provinces.provinceName FROM ((photographers INNER JOIN identity_photographers ON photographers.id= identity_photographers.id) INNER JOIN capstone2.servicepackages ON photographers.id = servicepackages.photographerId) INNER JOIN capstone2.provinces ON provinces.id= photographers.provinceId where identity_photographers.identityVerifyId=3 group by photographers.id ORDER BY photographers.id asc ";
	public static final String SEARCHALLINFOPHOTO1BYLOCATION="SELECT photographers.id,photographers.fullName,photographers.avatar,photographers.nickName,photographers.provinceId,photographers.workPlace,photographers.organize,identity_photographers.identityVerifyId,photographers.statusAccountId,photographers.countFollower,provinces.provinceName FROM ((photographers INNER JOIN identity_photographers ON photographers.id= identity_photographers.id) INNER JOIN capstone2.servicepackages ON photographers.id = servicepackages.photographerId) INNER JOIN capstone2.provinces ON provinces.id= photographers.provinceId WHERE photographers.provinceId=? and identity_photographers.identityVerifyId=3 group by photographers.id ORDER BY photographers.id asc  ";
	public static final String SEARCHALLINFOPHOTO2BYLOCATION="SELECT photographers.id,photographers.fullName,photographers.avatar,photographers.nickName,photographers.provinceId,photographers.workPlace,photographers.organize,identity_photographers.identityVerifyId,photographers.statusAccountId,photographers.countFollower,provinces.provinceName FROM ((photographers INNER JOIN identity_photographers ON photographers.id= identity_photographers.id) INNER JOIN capstone2.servicepackages ON photographers.id = servicepackages.photographerId) INNER JOIN capstone2.provinces ON provinces.id= photographers.provinceId WHERE servicepackages.categoryId=? and identity_photographers.identityVerifyId=3 group by photographers.id ORDER BY photographers.id asc  ";
	public static final String SEARCHALLINFOPHOTO123BYLOCATION="SELECT photographers.id,photographers.fullName,photographers.avatar,photographers.nickName,photographers.provinceId,photographers.workPlace,photographers.organize,identity_photographers.identityVerifyId,photographers.statusAccountId,photographers.countFollower,provinces.provinceName FROM ((photographers INNER JOIN identity_photographers ON photographers.id= identity_photographers.id) INNER JOIN capstone2.servicepackages ON photographers.id = servicepackages.photographerId) INNER JOIN capstone2.provinces ON provinces.id= photographers.provinceId WHERE servicepackages.categoryId=? and identity_photographers.identityVerifyId=3 and photographers.provinceId=? and MATCH(nickName) AGAINST(?) group by photographers.id ORDER BY photographers.id asc ";
	public static final String SEARCHALLINFOPHOTO12BYLOCATION = "SELECT photographers.id,photographers.fullName,photographers.avatar,photographers.nickName,photographers.provinceId,photographers.workPlace,photographers.organize,identity_photographers.identityVerifyId,photographers.statusAccountId,photographers.countFollower,provinces.provinceName FROM ((photographers INNER JOIN identity_photographers ON photographers.id= identity_photographers.id) INNER JOIN capstone2.servicepackages ON photographers.id = servicepackages.photographerId) INNER JOIN capstone2.provinces ON provinces.id= photographers.provinceId WHERE servicepackages.categoryId=? and identity_photographers.identityVerifyId=3 and photographers.provinceId=? group by photographers.id ORDER BY photographers.id asc LIMIT ";
	public static final String SEARCHALLINFOPHOTO3BYLOCATION = "SELECT photographers.id,photographers.fullName,photographers.avatar,photographers.nickName,photographers.provinceId,photographers.workPlace,photographers.organize,identity_photographers.identityVerifyId,photographers.statusAccountId,photographers.countFollower,provinces.provinceName FROM ((photographers INNER JOIN identity_photographers ON photographers.id= identity_photographers.id) INNER JOIN capstone2.servicepackages ON photographers.id = servicepackages.photographerId) INNER JOIN capstone2.provinces ON provinces.id= photographers.provinceId WHERE identity_photographers.identityVerifyId=3 and MATCH(nickName) AGAINST(?) group by photographers.id ORDER BY photographers.id asc ";
	public static final String SEARCHALLINFOPHOTO23BYLOCATION = "SELECT photographers.id,photographers.fullName,photographers.avatar,photographers.nickName,photographers.provinceId,photographers.workPlace,photographers.organize,identity_photographers.identityVerifyId,photographers.statusAccountId,photographers.countFollower,provinces.provinceName FROM ((photographers INNER JOIN identity_photographers ON photographers.id= identity_photographers.id) INNER JOIN capstone2.servicepackages ON photographers.id = servicepackages.photographerId) INNER JOIN capstone2.provinces ON provinces.id= photographers.provinceId WHERE servicepackages.categoryId=? and identity_photographers.identityVerifyId=3 and MATCH(nickName) AGAINST(?) group by photographers.id ORDER BY photographers.id asc ";
	public static final String SEARCHALLINFOPHOTO13BYLOCATION = "SELECT photographers.id,photographers.fullName,photographers.avatar,photographers.nickName,photographers.provinceId,photographers.workPlace,photographers.organize,identity_photographers.identityVerifyId,photographers.statusAccountId,photographers.countFollower,provinces.provinceName FROM ((photographers INNER JOIN identity_photographers ON photographers.id= identity_photographers.id) INNER JOIN capstone2.servicepackages ON photographers.id = servicepackages.photographerId) INNER JOIN capstone2.provinces ON provinces.id= photographers.provinceId WHERE  identity_photographers.identityVerifyId=3 and photographers.provinceId=? and MATCH(nickName) AGAINST(?) group by photographers.id ORDER BY photographers.id asc ";
	//searchPhoto by id
	public static final String SEARCHPHOTOGRAPHERBYID="SELECT photographers.id,photographers.fullName,photographers.avatar,photographers.nickName,photographers.provinceId,photographers.workPlace,photographers.organize,identity_photographers.identityVerifyId,photographers.statusAccountId,photographers.countFollower,provinces.provinceName FROM ((photographers INNER JOIN identity_photographers ON photographers.id= identity_photographers.id) INNER JOIN capstone2.servicepackages ON photographers.id = servicepackages.photographerId) INNER JOIN capstone2.provinces ON provinces.id= photographers.provinceId WHERE photographers.id=? ";
//xác minh photo
	public static final String IdentityPhotographer="UPDATE identity_operaadmin SET identity_operaadmin.adminID=?,identity_operaadmin.createDate=now() where  identity_operaadmin.photographerId=? ";
	public static final String AcceptIdentity="UPDATE identity_photographers SET identity_photographers.identityVerifyId=3 WHERE identity_photographers.id=?";
	public static final String RejectIdentity="UPDATE identity_photographers SET identity_photographers.frontPhoto=null,identity_photographers.backPhoto=null,identity_photographers.fullPhoto=null,identity_photographers.identityVerifyId=1 WHERE identity_photographers.id=?";
	public static final String AddIdentityPhotographer="INSERT INTO identity_operaadmin (identity_operaadmin.photographerId) VALUES (?)";


}
